// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFYJ48ycz32N-RejgjyoaZMouqdF-qa6I',
    appId: '1:227237803223:web:e0ef61abadf478ad71ac92',
    messagingSenderId: '227237803223',
    projectId: 'ecommerceflutter-35c36',
    authDomain: 'ecommerceflutter-35c36.firebaseapp.com',
    storageBucket: 'ecommerceflutter-35c36.appspot.com',
    measurementId: 'G-C0Q0ZF7SH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiWPE-3VOdcN43mza1p-VPQ2TSqbsALq8',
    appId: '1:227237803223:android:8db1cbd9e3ee1df971ac92',
    messagingSenderId: '227237803223',
    projectId: 'ecommerceflutter-35c36',
    storageBucket: 'ecommerceflutter-35c36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZM1rw23HwwWzvcLEdEjwOuxzPMzRXA84',
    appId: '1:227237803223:ios:d56c11ba42c914f971ac92',
    messagingSenderId: '227237803223',
    projectId: 'ecommerceflutter-35c36',
    storageBucket: 'ecommerceflutter-35c36.appspot.com',
    androidClientId: '227237803223-3j9csfjklinptbf05i8nqito1e6hsi2g.apps.googleusercontent.com',
    iosClientId: '227237803223-cma9qsu32908kkg26r9979ts25p9k682.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZM1rw23HwwWzvcLEdEjwOuxzPMzRXA84',
    appId: '1:227237803223:ios:d56c11ba42c914f971ac92',
    messagingSenderId: '227237803223',
    projectId: 'ecommerceflutter-35c36',
    storageBucket: 'ecommerceflutter-35c36.appspot.com',
    androidClientId: '227237803223-3j9csfjklinptbf05i8nqito1e6hsi2g.apps.googleusercontent.com',
    iosClientId: '227237803223-cma9qsu32908kkg26r9979ts25p9k682.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFYJ48ycz32N-RejgjyoaZMouqdF-qa6I',
    appId: '1:227237803223:web:447c82e3ee3368d171ac92',
    messagingSenderId: '227237803223',
    projectId: 'ecommerceflutter-35c36',
    authDomain: 'ecommerceflutter-35c36.firebaseapp.com',
    storageBucket: 'ecommerceflutter-35c36.appspot.com',
    measurementId: 'G-JV5NJ9663H',
  );

}